/**
 * diagnostics.ts — All /api/diag/* and /api/diagnostics/* service calls
 *
 * Each function is a typed, single-responsibility API call.
 * Used exclusively by React Query hooks — never called directly from components.
 */

import { api } from './api';
import type { AthenaData } from '@types-athena';

// ── Query keys — used by React Query for cache management ─────────────────────

export const QUERY_KEYS = {
  diagData:    ['diag', 'data']    as const,
  figureList:  ['diag', 'figures'] as const,
} as const;

// ── Cache TTLs ────────────────────────────────────────────────────────────────

export const STALE_TIMES = {
  diagData:   5 * 60 * 1000,   // 5 minutes — DB doesn't change mid-session
  figureList: 60 * 1000,        // 1 minute — figures update after a run
} as const;

// ── Response shapes ───────────────────────────────────────────────────────────

export interface FigureListResponse {
  figures:  string[];
  last_run: number;   // Unix timestamp (seconds), 0 if never run
}

// ── API calls ─────────────────────────────────────────────────────────────────

/**
 * Fetch all computed diagnostic metrics.
 * Drives the entire Athena dashboard.
 */
export async function fetchDiagData(): Promise<AthenaData> {
  const { data } = await api.get<AthenaData>('/diag/data');
  return data;
}

/**
 * List available figure PNGs generated by the last diagnostic run.
 */
export async function fetchFigureList(): Promise<FigureListResponse> {
  const { data } = await api.get<FigureListResponse>('/diagnostics/figures');
  return data;
}

/**
 * Resolve the URL for a specific figure image.
 * Used directly in <img src> — not a fetch call.
 */
export function getFigureUrl(filename: string): string {
  return `/api/diagnostics/figures/${encodeURIComponent(filename)}`;
}

/**
 * Check whether the Flask server is reachable.
 * Used by the connection status indicator in TopBar.
 */
export async function checkServerHealth(): Promise<boolean> {
  try {
    await api.get('/diagnostics/figures', { timeout: 3_000 });
    return true;
  } catch {
    return false;
  }
}
