import SwiftUI
import Charts

@MainActor final class InsightsViewModel:ObservableObject{@Published var data:LossReviewResponse?;@Published var error:String?;func load(_ url:String)async{do{data=try await APIClient(baseURL:url).insights();error=nil}catch{self.error=error.localizedDescription}}}
struct InsightsView:View{
    @EnvironmentObject var settings:AppSettings;@StateObject private var vm=InsightsViewModel()
    var body:some View{NavigationStack{ZStack{AppTheme.background.ignoresSafeArea();ScrollView{VStack(spacing:16){if let d=vm.data{HStack{MetricView(label:"Resolved",value:"\(d.summary.resolved)");MetricView(label:"Win rate",value:d.summary.winRate.map{String(format:"%.1f%%",$0)} ?? "—");MetricView(label:"Large total misses",value:"\(d.summary.largeTotalMisses)",tint:d.summary.largeTotalMisses>0 ? AppTheme.gold:.white)}.panel();learningFlags(d.warnings);performanceChart(title:"Model performance",data:d.byType);performanceChart(title:"Totals direction",data:d.byDirection);performanceChart(title:"Probability calibration",data:d.probabilityBuckets);Text("Detailed loss analysis, calibration diagnostics, raw features and CSV exports remain available on the research website.").font(.caption).foregroundStyle(AppTheme.muted).panel()}else{EmptyState(icon:"brain.head.profile",title:"Insights unavailable",message:vm.error ?? "Loading model health…")}}.padding(16)}}.navigationTitle("Model Insights")}.task{await vm.load(settings.backendURL)}.refreshable{await vm.load(settings.backendURL)}}
    private func learningFlags(_ warnings:[String])->some View{VStack(alignment:.leading,spacing:12){Label("Learning flags",systemImage:"lightbulb.max.fill").font(.headline).foregroundStyle(AppTheme.gold);if warnings.isEmpty{Text("No threshold-based warnings right now.").foregroundStyle(AppTheme.muted)}else{ForEach(warnings,id:\.self){Text("• "+$0).font(.subheadline).foregroundStyle(.white.opacity(0.82))}}}.frame(maxWidth:.infinity,alignment:.leading).panel()}
    private func performanceChart(title:String,data:[PerformanceBucket])->some View{VStack(alignment:.leading,spacing:14){Text(title).font(.headline);Chart(data){item in BarMark(x:.value("Group",item.label),y:.value("Win rate",item.winRate ?? 0)).foregroundStyle(AppTheme.gold.gradient).cornerRadius(5);RuleMark(y:.value("Reference",52.4)).foregroundStyle(Color.white.opacity(0.25)).lineStyle(StrokeStyle(dash:[5]))}.chartYScale(domain:0...100).frame(height:190);HStack{ForEach(data){item in Text("\(item.label): n=\(item.n)").font(.caption2).foregroundStyle(AppTheme.muted)}}}.panel()}
}
