ABBR_TO_FULL = {
"YAN": "New York Yankees",
"BOS": "Boston Red Sox",
"BRE": "Boston Red Sox",
"TB": "Tampa Bay Rays",
"RAY": "Tampa Bay Rays",
"BAL": "Baltimore Orioles",
"ORI": "Baltimore Orioles",
"TOR": "Toronto Blue Jays",
"JAY": "Toronto Blue Jays",
"CLE": "Cleveland Guardians",
"GUA": "Cleveland Guardians",
"CWS": "Chicago White Sox",
"SOX": "Chicago White Sox",
"DET": "Detroit Tigers",
"TIG": "Detroit Tigers",
"KC": "Kansas City Royals",
"ROY": "Kansas City Royals",
"MIN": "Minnesota Twins",
"TWI": "Minnesota Twins",
"HOU": "Houston Astros",
"AST": "Houston Astros",
"LAA": "Los Angeles Angels",
"ANG": "Los Angeles Angels",
"OAK": "Oakland Athletics",
"ATH": "Oakland Athletics",
"SEA": "Seattle Mariners",
"MAR": "Seattle Mariners",
"TEX": "Texas Rangers",
"RAN": "Texas Rangers",
"ATL": "Atlanta Braves",
"BRA": "Atlanta Braves",
"WSH": "Washington Nationals",
"NAT": "Washington Nationals",
"PHI": "Philadelphia Phillies",
"NYM": "New York Mets",
"MET": "New York Mets",
"MIA": "Miami Marlins",
"STL": "St. Louis Cardinals",
"CAR": "St. Louis Cardinals",
"MIL": "Milwaukee Brewers",
"CHC": "Chicago Cubs",
"CUB": "Chicago Cubs",
"PIT": "Pittsburgh Pirates",
"PIR": "Pittsburgh Pirates",
"CIN": "Cincinnati Reds",
"RED": "Cincinnati Reds",
"LAD": "Los Angeles Dodgers",
"SD": "San Diego Padres",
"SF": "San Francisco Giants",
"ARI": "Arizona Diamondbacks",
"DIA": "Arizona Diamondbacks",
"COL": "Colorado Rockies",
"ROC": "Colorado Rockies",
}


def get_full_name(abbr):

    return ABBR_TO_FULL.get(abbr, abbr)
